# Pull in the layer of the base image: ubuntu:15.04
FROM ubuntu:15.04

# Copy local directory to container
COPY . /app

# Build the application
RUN make /app

# Run the application
CMD python /app/app.py
