# Pull in the layer of the base image: alpine:3.10.3
                           

# Set maintainer label: maintainer=[YOUR-EMAIL]


# Set working directory: `/opt`


# Copy local file `main.go` to the working directory


# List items in the working directory (ls)


# Show content of the `main.go` during the build process (cat)
